### ISSUE TITLE
I hard forked zeronet. 

### ISSUE THREAD

**Issue by p2p-publisher** [imachug/talk#4]
.

**Comment by p2p-publisher** [comment]
Email: 7eUEFGDk2scRnG8k@protonmail.com

**Comment by imachug** [comment]
I prefer writing in public, if that's not a problem for you.

**Comment by p2p-publisher** [comment]
of course is not a  problem, just wanted to send you the source code before publishing it.

**Comment by imachug** [comment]
You can publish it to a private repository and invite me as a collaborator.

**Comment by p2p-publisher** [comment]
ok, delete this issue
